FIX_START_MORNING_WORKING_TIME = "08:25"
FIX_END_MORNING_WORKING_TIME = "12:08"
FIX_START_AFTERNOON_WORKING_TIME = "13:00"
FIX_END_AFTERNOON_WORKING_TIME = "17:33"


FIX_START_MORNING_WORKING_MESSAGE = "Bắt đầu ngày làm việc"
FIX_END_MORNING_WORKING_MESSAGE = "Kết thúc giờ làm việc buổi sáng"
FIX_START_AFTERNOON_WORKING_MESSAGE = "Bắt đầu giờ làm việc buổi chiều"
FIX_END_AFTERNOON_WORKING_MESSAGE = "Kết thúc ngày làm việc"